### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Eelke76**
Resolves two reasons why downloading of the favicon might fail. The login page does not provide a favicon while the homepage of the website does. The favicon can only be downloaded when the cookie set by the page is present.

### CODE REVIEW

**Comment by navossoc** [comment]
Looks interesting. I agree with the cookie change, but I have some doubts about the redirect.
I'll take a closer look tomorrow.

Cheers.

**Comment by koppor** [comment]
@navossoc I found this plugin and it seems to be maintained - the described functionality sounds interesting, too. May I ask whether you found time to take a closer look?

**Comment by navossoc** [comment]
@koppor It is. I'll look, I promise...

I was focusing my free time on this:
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/issues/55

To be totally honest. I'm using this free time to play a little bit, something I haven't done in a long time.
Damn you no man's sky expeditions update

Hang in there ;)

**Comment by navossoc** [comment]
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).

Thanks @Eelke76 for your contribution ;)

**Pull request closed without merging**
