### PR TITLE
Option to use Google S2 API for fetching icon 

### LINKED ISSUE #21: Fail to find favicon for opensensemap.org
Hi,

YAFD is failing to find the favicon for https://opensensemap.org. 
I believe it should be finding an icon based on the following tag :
<link rel="icon" href="images/a86afe07.favicon.svg">

### LINKED ISSUE #26: Support Icons behind a Basic Auth Flow
Some websites have a Basic Auth implementation that prevents YAFD from grabbing an icon that would be in the HTML after being authenticated. The username and password are already there, so there is no reason not to automatically authenticate when trying to grab the icon.

For obvious security and privacy reasons, this should be behind an option that is disabled to default.

### LINKED ISSUE #37: download FavIco failed
https://pixabay.com/

the plugin download this website FavIco failed . Maybe it contains many icons .

### LINKED ISSUE #44: Unable to find favicon for seur.com
URL: https://www.seur.com/acceso-web-privada.do
imagen

Plugin version:
imagen

### LINKED ISSUE #45: Failed to retrieve favicon from rei.com
I have an entry for rei.com and I noticed it's not able to pull its favicon. However, hitting https://www.rei.com/favicon.ico directly from the browser seems to work.

### LINKED ISSUE #47: did not work on https://digid.nl/inloggen
did not work on https://digid.nl/inloggen

### LINKED ISSUE #48: Failed to retrieve icon from FlightRadar24
The web site doesn't respond to the usual <url>/favicon.ico but it lists several icons available:

```
<link rel="apple-touch-icon" sizes="57x57" href="https://www.flightradar24.com/static/favicons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="https://www.flightradar24.com/static/favicons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="https://www.flightradar24.com/static/favicons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="https://www.flightradar24.com/static/favicons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="https://www.flightradar24.com/static/favicons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="https://www.flightradar24.com/static/favicons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="https://www.flightradar24.com/static/favicons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="https://www.flightradar24.com/static/favicons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="https://www.flightradar24.com/static/favicons/apple-icon-180x180.png">
<link rel="icon" type="image/svg+xml" href="https://www.flightradar24.com/static/favicons/favicon.svg"/>
<link rel="alternate icon" type="image/png" sizes="192x192" href="https://www.flightradar24.com/static/favicons/android-icon-192x192.png">
<link rel="alternate icon" type="image/png" sizes="32x32" href="https://www.flightradar24.com/static/favicons/favicon-32x32.png">
<link rel="alternate icon" type="image/png" sizes="96x96" href="https://www.flightradar24.com/static/favicons/favicon-96x96.png">
<link rel="alternate icon" type="image/png" sizes="16x16" href="https://www.flightradar24.com/static/favicons/favicon-16x16.png">
<link rel="manifest" href="https://www.flightradar24.com/static/favicons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="https://www.flightradar24.com/static/favicons/ms-icon-144x144.png">
```

I'm wondering if YAFD could use one of the options listed.

### LINKED ISSUE #49: Failed to retrieve icon for 3D Content Central
This one is weird. I can see an favicon for it at https://www.3dcontentcentral.com/favicon.ico but YAFD didn't detect it. I had to download it manually into KeePass.

### LINKED ISSUE #50: Quizlet DOT com
Opening site shows a favicon in browser tab.  YAFD doesn't see it.   Looking at page source and searching for 'favicon' I found it readily enough - just weirdly named, is all.

"https://assets.quizlet.com/a/j/dist/i/favicon.6e263725c926227.ico"

Just thought you'd want to know.

Info:

Windows 10 20H2 (19042.804)
KeePass v2.47 x64
YAFD v1.2.4.0

### LINKED ISSUE #51: TechSoup DOT org
YAFD doesn't find it, but searching page source finds it readily enough:

"https://www.techsoup.org/_layouts/15/TechSoup/ui/images/favicon.png"

Info:

Windows 10 20H2 (19042.804)
KeePass v2.47 x64
YAFD v1.2.4.0

### LINKED ISSUE #52: Neverware Zendesk site
Neverware (now owned by Google) has a ZenDesk site for FAQs and questions about their Neverware CloudReady Chrome OS for home, education and enterprise users.  URL:  https://neverware.zendesk.com/hc/en-us (English).  YAFD cannot find favicon seen in browser tab, but source search finds it:

"//theme.zdassets.com/theme_assets/187734/df7ad117882f0a0b8d3b4b06b43b09bb29ada9e3.png"

Info:

Windows 10 20H2 (19042.804)
KeePass v2.47 x64
YAFD v1.2.4.0

### LINKED ISSUE #53: TireRack DOT com
Browser tab shows a favicon, but I CANNOT find it in the source code.  I suspect it is loading via JS or some other manner.

Info:

Windows 10 20H2 (19042.804)
KeePass v2.47 x64
YAFD v1.2.4.0

### LINKED ISSUE #57: Icon not found for iTouchless.com
Entry URL: https://itouchless.com/account/login

Relevant code in the webpage:
```html
  <!-- Favicons
================================================== -->

  <link rel="shortcut icon" href="//cdn.shopify.com/s/files/1/0399/5942/9281/t/4/assets/favicon.png?v=15106769190101230059">
```

The icon is actually a WebP image, which KeePass does not natively support. When manually importing, I had to convert it to a PNG as a workaround.

### LINKED ISSUE #60: Check if the file size for the favicon is too big
I encountered a problem with Keepass2Android, because a downloaded favicon was too huge too handle it.

Therefore a check if the file size is realistic would be nice.

An example for a website where the downloaded favicon is huge is https://anchor.fm/.

The downloaded favicon is 11760x11760 pixel big and has a filesize of 846kb.

### PR DESCRIPTION
**Pull request by Henri-J-Norden**
### Changes

- Option in the Tools->YAFD menu to use Google S2 API to fetch icons. This returns an icon based on the domain name, so will likely return an incorrect icon if a sub-page has a different icon than at URI path `/` - but I did not test this.
- Always returns a 16x16 icon to keep DB size low.
- For debugging/testing: added `plgx-build-install-run-loop.bat` script to automatically install the plugin and run KeePass.

### Relevant issues
Fix #60, fix #57, fix #53, fix #52, fix #51, fix #50, fix #49, fix #47, fix #45, fix #44, fix #37, fix #21 

clipboard

Fixes partially #48, https://flightradar24.com/ works, but not https://www.flightradar24.com/

Partially implements #42 (16x16 icons only), but could also be done using the [Google S2 API](https://stackoverflow.com/questions/38599939/how-to-get-larger-favicon-from-googles-api/46044485).

Fixes partially maybe(?) #26, if the icon is the same as for the "domain" as given by Google.

### CODE REVIEW

**Comment by navossoc** [comment]
Nice job!

I'll make a few minor changes and I let you now.

This week I will release the next version. with a few improvements, including your PR. 

If I recall correctly, KeePass now display icons larger than 16x16 somewhere in the UI.
I read that on the changelog I think. I need to search it.

[]'s

**Comment by Hrxn** [comment]
Yeah, always using 32x32 would be nice, in my opinion. Does this Google API provide that?

**Comment by navossoc** [comment]
> Yeah, always using 32x32 would be nice, in my opinion. Does this Google API provide that?

Yes, it does...
https://www.google.com/s2/favicons?domain_url=google.com&sz=32

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
wrong place? Just  a note for the favicon fetching, there is other more "private" solution existing such as for example:


https://icons.duckduckgo.com/ip3/keepass.info.ico


[https://icons.duckduckgo.com/ip3/keepass.info.ico
](https://icons.duckduckgo.com/ip3/keepass.info.ico
)
https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/ip3/keepass.info.ico
[https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/ip3/keepass.info.ico](https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/ip3/keepass.info.ico)

**Comment by navossoc** [comment]
TBH I'm thinking in ignore this and make a "custom provider" option.
@Henri-J-Norden gave me the initial push I needed haha.

Since this favicon services return the image directly, they all should be compatible.

I made a small list so far:

**Providers:**
https://icons.duckduckgo.com/ip3/{URL:HOST}.ico
https://api.faviconkit.com/{URL:HOST}/{YAFD:ICON_SIZE}
http://www.google.com/s2/favicons?domain={URL:HOST}&sz={YAFD:ICON_SIZE}
https://favicon.yandex.net/favicon/{URL:HOST}

**Placeholders:**
{URL:HOST} = www.domain.com
{YAFD:ICON_SIZE} = 48

**Comment by navossoc** [comment]
Well, well, well...

Anyone is using it? Any issues? Should we release it on the wild? hahaha
I didn't use it too much in the last week, but as far I can tell it's working as expected.

**Comment by navossoc** [comment]
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).

Thanks @Henri-J-Norden for the push we needed to make this feature happens ;)

**Pull request closed without merging**
