### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nolddor**
Added additional hint for Linux users (such us Debian 9)

### CODE REVIEW

**Comment by navossoc** [comment]
I'm not 100% sure, but I think `mono-devel` is all you need, maybe `ca-certificates-mono`.

I'll take a look later tonight.

Thanks.

**Comment by nolddor** [comment]
It can be, the problem was that using Debian 9 i was unable to make it work this plugins.
After checking the official KeePass website. It says that for some plugins it may be required the mono-complete package. After install it the complement worked.

If only mono-devel if needed I suggest to edit my PR and change the package name but is would me great to have a hint for users like me that doesn't underestand what package is needed.

Kind Regards

**Comment by navossoc** [comment]
I did a clean install on a Debian 9 vm.
The package `mono-devel` was enough.

The only problem with mono that is shipped with debian is that it is a little bit old.
If you want better results, you should upgrade it.

There is a few issues here where I explain about it.
Maybe create a wiki entry for it.

What do you think about?

[]'s

**Comment by nolddor** [comment]
Sure ;)

I believe is enough for the majority of us.
Thanks!

**Comment by navossoc** [comment]
Any suggestion?
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/wiki/Linux-install

**Pull request closed without merging**
